spring.application.name=core
spring.profiles.default=local

# H2 Database Configuration
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

panel.security.h2-console-enabled=false
panel.security.ping-federate.registration-id=pingfed
panel.security.ping-federate.logout-success-url=/
panel.security.frontend-base-url=${PANEL_SECURITY_FRONTEND_BASE_URL:}
panel.security.claim-mapping.username-claim=preferred_username
panel.security.claim-mapping.display-name-claim=name
panel.security.claim-mapping.email-claim=email
panel.security.claim-mapping.groups-claim=groups
panel.security.claim-mapping.entitlements-claim=entitlements
panel.security.claim-mapping.permissions-claim=permissions
panel.security.claim-mapping.data-scopes-claim=data_scopes
